export const CHORE_EMOJI_CATEGORIES = {
  smileysAndPeople: {
    name: 'Smileys & People',
    icon: '😀',
    emojis: [
      { emoji: '😀', name: 'grinning face', keywords: ['happy', 'smile', 'joy'] },
      { emoji: '😃', name: 'grinning face with big eyes', keywords: ['happy', 'smile', 'joy'] },
      { emoji: '😄', name: 'grinning face with smiling eyes', keywords: ['happy', 'smile', 'joy'] },
      { emoji: '😁', name: 'beaming face with smiling eyes', keywords: ['happy', 'smile', 'joy'] },
      { emoji: '😊', name: 'smiling face with smiling eyes', keywords: ['happy', 'blush'] },
      { emoji: '🥰', name: 'smiling face with hearts', keywords: ['love', 'happy'] },
      { emoji: '😍', name: 'smiling face with heart-eyes', keywords: ['love', 'happy'] },
      { emoji: '🤩', name: 'star-struck', keywords: ['excited', 'happy'] },
      { emoji: '😎', name: 'smiling face with sunglasses', keywords: ['cool', 'sunglasses'] },
      { emoji: '🤗', name: 'hugging face', keywords: ['hug', 'love'] },
      { emoji: '👋', name: 'waving hand', keywords: ['hello', 'bye', 'wave'] },
      { emoji: '🤚', name: 'raised back of hand', keywords: ['hand', 'stop'] },
      { emoji: '✋', name: 'raised hand', keywords: ['hand', 'stop', 'high five'] },
      { emoji: '👍', name: 'thumbs up', keywords: ['good', 'yes', 'approve'] },
      { emoji: '👎', name: 'thumbs down', keywords: ['bad', 'no', 'disapprove'] },
      { emoji: '✊', name: 'raised fist', keywords: ['fist', 'power'] },
      { emoji: '👊', name: 'oncoming fist', keywords: ['fist bump', 'punch'] },
      { emoji: '🤝', name: 'handshake', keywords: ['shake hands', 'agreement'] },
      { emoji: '👏', name: 'clapping hands', keywords: ['clap', 'applause', 'good job'] },
      { emoji: '🙌', name: 'raising hands', keywords: ['celebrate', 'hooray'] },
      { emoji: '🧒', name: 'child', keywords: ['kid', 'boy', 'girl', 'person'] },
      { emoji: '👶', name: 'baby', keywords: ['infant', 'newborn'] },
      { emoji: '👦', name: 'boy', keywords: ['child', 'son'] },
      { emoji: '👧', name: 'girl', keywords: ['child', 'daughter'] },
      { emoji: '👨', name: 'man', keywords: ['adult', 'male', 'dad'] },
      { emoji: '👩', name: 'woman', keywords: ['adult', 'female', 'mom'] },
      { emoji: '👪', name: 'family', keywords: ['parents', 'children', 'together'] },
      { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle', 'power'] },
    ],
  },
  cleaning: {
    name: 'Cleaning',
    icon: '🧹',
    emojis: [
      { emoji: '🧹', name: 'broom', keywords: ['sweep', 'clean', 'floor'] },
      { emoji: '🧽', name: 'sponge', keywords: ['wash', 'clean', 'scrub', 'dishes'] },
      { emoji: '🗑️', name: 'trash', keywords: ['garbage', 'bin', 'waste'] },
      { emoji: '🧼', name: 'soap', keywords: ['wash', 'clean', 'hands', 'hygiene'] },
      { emoji: '🧺', name: 'basket', keywords: ['laundry', 'clothes', 'hamper'] },
      { emoji: '🚿', name: 'shower', keywords: ['wash', 'clean', 'bath'] },
      { emoji: '🛁', name: 'bathtub', keywords: ['bath', 'wash', 'clean'] },
      { emoji: '🚽', name: 'toilet', keywords: ['bathroom', 'clean', 'potty'] },
      { emoji: '🪣', name: 'bucket', keywords: ['water', 'clean', 'mop'] },
      { emoji: '🪟', name: 'window', keywords: ['clean', 'glass', 'windex'] },
      { emoji: '🧴', name: 'lotion bottle', keywords: ['soap', 'clean', 'spray'] },
      { emoji: '🧻', name: 'roll of paper', keywords: ['toilet paper', 'tissue'] },
      { emoji: '🪥', name: 'toothbrush', keywords: ['brush teeth', 'hygiene', 'dental', 'tooth'] },
      { emoji: '🪒', name: 'razor', keywords: ['shave', 'groom'] },
      { emoji: '🧽', name: 'sponge', keywords: ['wash', 'clean', 'scrub'] },
    ],
  },
  personal: {
    name: 'Personal Care',
    icon: '🛏️',
    emojis: [
      { emoji: '🛏️', name: 'bed', keywords: ['make bed', 'bedroom', 'sleep'] },
      { emoji: '🛌', name: 'person in bed', keywords: ['sleep', 'rest', 'bedtime'] },
      { emoji: '👕', name: 'shirt', keywords: ['clothes', 'laundry', 'dress'] },
      { emoji: '👔', name: 'necktie', keywords: ['formal', 'dress up'] },
      { emoji: '👗', name: 'dress', keywords: ['clothes', 'outfit'] },
      { emoji: '👖', name: 'jeans', keywords: ['pants', 'clothes'] },
      { emoji: '🧦', name: 'socks', keywords: ['clothes', 'feet'] },
      { emoji: '👟', name: 'running shoe', keywords: ['shoes', 'tidy', 'organize'] },
      { emoji: '🥾', name: 'hiking boot', keywords: ['shoes', 'boots'] },
      { emoji: '👞', name: 'mans shoe', keywords: ['shoes', 'dress'] },
      { emoji: '🧸', name: 'teddy bear', keywords: ['toys', 'play', 'clean up'] },
      { emoji: '🎒', name: 'backpack', keywords: ['school', 'bag', 'pack'] },
      { emoji: '🦷', name: 'tooth', keywords: ['brush teeth', 'hygiene', 'dental'] },
      { emoji: '🪥', name: 'toothbrush', keywords: ['brush teeth', 'hygiene', 'dental'] },
      { emoji: '🧴', name: 'lotion bottle', keywords: ['soap', 'hygiene', 'skincare'] },
      { emoji: '💇', name: 'person getting haircut', keywords: ['hair', 'haircut', 'groom'] },
      { emoji: '🛀', name: 'person taking bath', keywords: ['bath', 'clean', 'wash'] },
    ],
  },
  toys: {
    name: 'Toys & Play',
    icon: '🧸',
    emojis: [
      { emoji: '🧸', name: 'teddy bear', keywords: ['toy', 'stuffed animal', 'bear'] },
      { emoji: '🪀', name: 'yo-yo', keywords: ['toy', 'play'] },
      { emoji: '🪁', name: 'kite', keywords: ['toy', 'fly', 'outdoor'] },
      { emoji: '🎮', name: 'video game', keywords: ['game', 'play', 'console'] },
      { emoji: '🎲', name: 'dice', keywords: ['game', 'play', 'board game'] },
      { emoji: '🧩', name: 'puzzle piece', keywords: ['puzzle', 'game', 'play'] },
      { emoji: '🎯', name: 'direct hit', keywords: ['target', 'game', 'bullseye'] },
      { emoji: '🎨', name: 'artist palette', keywords: ['art', 'paint', 'creative'] },
      { emoji: '🖍️', name: 'crayon', keywords: ['color', 'draw', 'art'] },
      { emoji: '✏️', name: 'pencil', keywords: ['write', 'draw', 'homework'] },
      { emoji: '📝', name: 'memo', keywords: ['write', 'note', 'homework'] },
      { emoji: '📚', name: 'books', keywords: ['read', 'study', 'homework', 'tidy'] },
      { emoji: '📖', name: 'open book', keywords: ['read', 'study', 'book'] },
      { emoji: '🎵', name: 'musical note', keywords: ['music', 'practice', 'instrument'] },
      { emoji: '🎸', name: 'guitar', keywords: ['music', 'instrument', 'practice'] },
      { emoji: '🥁', name: 'drum', keywords: ['music', 'instrument', 'practice'] },
    ],
  },
  pets: {
    name: 'Pets',
    icon: '🐶',
    emojis: [
      { emoji: '🐶', name: 'dog face', keywords: ['pet', 'walk dog', 'feed', 'puppy'] },
      { emoji: '🐕', name: 'dog', keywords: ['pet', 'walk', 'feed'] },
      { emoji: '🐱', name: 'cat face', keywords: ['pet', 'feed cat', 'litter', 'kitten'] },
      { emoji: '🐈', name: 'cat', keywords: ['pet', 'feed', 'litter'] },
      { emoji: '🐾', name: 'paw prints', keywords: ['pet', 'animal', 'clean'] },
      { emoji: '🦴', name: 'bone', keywords: ['dog', 'treat', 'pet'] },
      { emoji: '🐟', name: 'fish', keywords: ['pet', 'feed fish', 'tank'] },
      { emoji: '🐠', name: 'tropical fish', keywords: ['pet', 'aquarium', 'feed'] },
      { emoji: '🐇', name: 'rabbit', keywords: ['pet', 'bunny', 'feed'] },
      { emoji: '🐹', name: 'hamster', keywords: ['pet', 'feed', 'cage'] },
      { emoji: '🐦', name: 'bird', keywords: ['pet', 'feed', 'cage'] },
      { emoji: '🐢', name: 'turtle', keywords: ['pet', 'feed', 'slow'] },
    ],
  },
  outdoor: {
    name: 'Outdoor & Yard',
    icon: '🌱',
    emojis: [
      { emoji: '🌱', name: 'seedling', keywords: ['garden', 'plants', 'water', 'grow'] },
      { emoji: '🌿', name: 'herb', keywords: ['weeds', 'garden', 'yard', 'plant'] },
      { emoji: '🌳', name: 'deciduous tree', keywords: ['tree', 'yard', 'nature'] },
      { emoji: '🌲', name: 'evergreen tree', keywords: ['tree', 'yard', 'nature'] },
      { emoji: '🌻', name: 'sunflower', keywords: ['flower', 'garden', 'plant'] },
      { emoji: '🌺', name: 'hibiscus', keywords: ['flower', 'garden', 'plant'] },
      { emoji: '🌹', name: 'rose', keywords: ['flower', 'garden', 'plant'] },
      { emoji: '🌷', name: 'tulip', keywords: ['flower', 'garden', 'plant'] },
      { emoji: '🍂', name: 'fallen leaf', keywords: ['rake', 'leaves', 'yard', 'autumn'] },
      { emoji: '🍃', name: 'leaf fluttering', keywords: ['leaves', 'yard', 'rake'] },
      { emoji: '💧', name: 'droplet', keywords: ['water', 'plants', 'garden'] },
      { emoji: '💦', name: 'sweat droplets', keywords: ['water', 'splash', 'wash'] },
      { emoji: '🚗', name: 'car', keywords: ['wash car', 'clean', 'vehicle'] },
      { emoji: '🚙', name: 'sport utility vehicle', keywords: ['car', 'wash', 'vehicle'] },
      { emoji: '🚲', name: 'bicycle', keywords: ['bike', 'put away', 'garage', 'ride'] },
      { emoji: '⛷️', name: 'skier', keywords: ['ski', 'snow', 'sport'] },
    ],
  },
  kitchen: {
    name: 'Kitchen & Food',
    icon: '🍽️',
    emojis: [
      { emoji: '🍽️', name: 'fork and knife with plate', keywords: ['dishes', 'set table', 'eat', 'meal'] },
      { emoji: '🍴', name: 'fork and knife', keywords: ['utensils', 'eat', 'cutlery'] },
      { emoji: '🥄', name: 'spoon', keywords: ['utensil', 'eat', 'soup'] },
      { emoji: '🔪', name: 'kitchen knife', keywords: ['cut', 'cook', 'chef'] },
      { emoji: '🍳', name: 'cooking', keywords: ['cook', 'kitchen', 'food', 'egg', 'fry'] },
      { emoji: '🥘', name: 'shallow pan of food', keywords: ['cook', 'food', 'paella'] },
      { emoji: '🍲', name: 'pot of food', keywords: ['cook', 'stew', 'soup'] },
      { emoji: '🧊', name: 'ice', keywords: ['fridge', 'food', 'put away', 'cold'] },
      { emoji: '🥤', name: 'cup with straw', keywords: ['drink', 'beverage', 'cup'] },
      { emoji: '🧃', name: 'beverage box', keywords: ['juice', 'drink', 'kids'] },
      { emoji: '🍎', name: 'apple', keywords: ['food', 'groceries', 'put away', 'fruit'] },
      { emoji: '🍌', name: 'banana', keywords: ['food', 'fruit', 'groceries'] },
      { emoji: '🍊', name: 'orange', keywords: ['food', 'fruit', 'groceries'] },
      { emoji: '🍇', name: 'grapes', keywords: ['food', 'fruit', 'groceries'] },
      { emoji: '🍓', name: 'strawberry', keywords: ['food', 'fruit', 'groceries'] },
      { emoji: '🥕', name: 'carrot', keywords: ['vegetables', 'groceries', 'food'] },
      { emoji: '🥦', name: 'broccoli', keywords: ['vegetables', 'groceries', 'cook', 'food'] },
      { emoji: '🥬', name: 'leafy green', keywords: ['vegetables', 'salad', 'food'] },
      { emoji: '🌽', name: 'ear of corn', keywords: ['vegetables', 'food', 'groceries'] },
      { emoji: '🍞', name: 'bread', keywords: ['food', 'groceries', 'bakery'] },
      { emoji: '🥛', name: 'glass of milk', keywords: ['drink', 'milk', 'dairy'] },
      { emoji: '🧀', name: 'cheese wedge', keywords: ['food', 'dairy', 'groceries'] },
      { emoji: '🥚', name: 'egg', keywords: ['food', 'cook', 'breakfast'] },
      { emoji: '🍕', name: 'pizza', keywords: ['food', 'eat', 'dinner'] },
      { emoji: '🍔', name: 'hamburger', keywords: ['food', 'eat', 'lunch'] },
      { emoji: '🌮', name: 'taco', keywords: ['food', 'eat', 'dinner'] },
      { emoji: '🥗', name: 'green salad', keywords: ['food', 'healthy', 'vegetables'] },
    ],
  },
  activities: {
    name: 'Activities & Sports',
    icon: '⚽',
    emojis: [
      { emoji: '⚽', name: 'soccer ball', keywords: ['sport', 'football', 'play', 'exercise'] },
      { emoji: '🏀', name: 'basketball', keywords: ['sport', 'play', 'exercise'] },
      { emoji: '🏈', name: 'american football', keywords: ['sport', 'play', 'exercise'] },
      { emoji: '⚾', name: 'baseball', keywords: ['sport', 'play', 'exercise'] },
      { emoji: '🎾', name: 'tennis', keywords: ['sport', 'play', 'exercise'] },
      { emoji: '🏐', name: 'volleyball', keywords: ['sport', 'play', 'exercise'] },
      { emoji: '🏓', name: 'ping pong', keywords: ['sport', 'play', 'table tennis'] },
      { emoji: '🏸', name: 'badminton', keywords: ['sport', 'play', 'exercise'] },
      { emoji: '🥊', name: 'boxing glove', keywords: ['sport', 'exercise', 'fight'] },
      { emoji: '🏃', name: 'person running', keywords: ['run', 'exercise', 'jog'] },
      { emoji: '🚴', name: 'person biking', keywords: ['bike', 'exercise', 'ride'] },
      { emoji: '🏊', name: 'person swimming', keywords: ['swim', 'exercise', 'pool'] },
      { emoji: '🤸', name: 'person cartwheeling', keywords: ['gymnastics', 'exercise', 'flip'] },
      { emoji: '🧘', name: 'person in lotus position', keywords: ['yoga', 'meditate', 'relax'] },
      { emoji: '🎵', name: 'musical note', keywords: ['music', 'practice', 'sing'] },
      { emoji: '🎸', name: 'guitar', keywords: ['music', 'practice', 'instrument'] },
      { emoji: '🥁', name: 'drum', keywords: ['music', 'practice', 'instrument'] },
      { emoji: '🎹', name: 'musical keyboard', keywords: ['piano', 'music', 'practice'] },
    ],
  },
  objects: {
    name: 'Objects & Tools',
    icon: '🔧',
    emojis: [
      { emoji: '🔧', name: 'wrench', keywords: ['tool', 'fix', 'repair'] },
      { emoji: '🔨', name: 'hammer', keywords: ['tool', 'fix', 'build'] },
      { emoji: '⚒️', name: 'hammer and pick', keywords: ['tools', 'build'] },
      { emoji: '🪛', name: 'screwdriver', keywords: ['tool', 'fix', 'repair'] },
      { emoji: '🪚', name: 'carpentry saw', keywords: ['tool', 'cut', 'build'] },
      { emoji: '📦', name: 'package', keywords: ['box', 'deliver', 'organize'] },
      { emoji: '📫', name: 'closed mailbox with raised flag', keywords: ['mail', 'get mail', 'post'] },
      { emoji: '📪', name: 'closed mailbox with lowered flag', keywords: ['mail', 'get mail'] },
      { emoji: '🔑', name: 'key', keywords: ['lock', 'unlock', 'door'] },
      { emoji: '🪑', name: 'chair', keywords: ['sit', 'furniture', 'tidy'] },
      { emoji: '🚪', name: 'door', keywords: ['open', 'close', 'room'] },
      { emoji: '🪟', name: 'window', keywords: ['open', 'close', 'clean'] },
      { emoji: '💡', name: 'light bulb', keywords: ['light', 'idea', 'electricity'] },
      { emoji: '🕯️', name: 'candle', keywords: ['light', 'flame'] },
      { emoji: '🧺', name: 'basket', keywords: ['laundry', 'clothes', 'organize'] },
      { emoji: '🧴', name: 'lotion bottle', keywords: ['soap', 'clean', 'hygiene'] },
      { emoji: '🕶️', name: 'sunglasses', keywords: ['glasses', 'put away', 'organize', 'items'] },
      { emoji: '👓', name: 'glasses', keywords: ['eyeglasses', 'put away', 'organize'] },
      { emoji: '🎒', name: 'backpack', keywords: ['school', 'bag', 'organize'] },
      { emoji: '👜', name: 'handbag', keywords: ['bag', 'purse', 'organize'] },
      { emoji: '🧳', name: 'luggage', keywords: ['suitcase', 'travel', 'pack'] },
    ],
  },
  symbols: {
    name: 'Symbols',
    icon: '⭐',
    emojis: [
      { emoji: '⭐', name: 'star', keywords: ['favorite', 'good', 'reward'] },
      { emoji: '🌟', name: 'glowing star', keywords: ['sparkle', 'good job', 'reward'] },
      { emoji: '✨', name: 'sparkles', keywords: ['clean', 'shine', 'magic'] },
      { emoji: '💫', name: 'dizzy', keywords: ['sparkle', 'star', 'dizzy'] },
      { emoji: '🎉', name: 'party popper', keywords: ['celebrate', 'party', 'done'] },
      { emoji: '🎊', name: 'confetti ball', keywords: ['celebrate', 'party', 'done'] },
      { emoji: '🎈', name: 'balloon', keywords: ['celebrate', 'party', 'birthday'] },
      { emoji: '🎁', name: 'wrapped gift', keywords: ['present', 'gift', 'reward'] },
      { emoji: '🏆', name: 'trophy', keywords: ['win', 'champion', 'award'] },
      { emoji: '🥇', name: 'first place medal', keywords: ['gold', 'winner', 'first'] },
      { emoji: '🥈', name: 'second place medal', keywords: ['silver', 'second'] },
      { emoji: '🥉', name: 'third place medal', keywords: ['bronze', 'third'] },
      { emoji: '💯', name: 'hundred points', keywords: ['perfect', 'great', 'full score'] },
      { emoji: '✅', name: 'check mark button', keywords: ['done', 'complete', 'yes'] },
      { emoji: '✔️', name: 'check mark', keywords: ['done', 'complete', 'yes'] },
      { emoji: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'cancel'] },
      { emoji: '❤️', name: 'red heart', keywords: ['love', 'like', 'favorite'] },
      { emoji: '💚', name: 'green heart', keywords: ['love', 'like', 'eco'] },
      { emoji: '💙', name: 'blue heart', keywords: ['love', 'like', 'peace'] },
      { emoji: '💛', name: 'yellow heart', keywords: ['love', 'like', 'happy'] },
      { emoji: '🔔', name: 'bell', keywords: ['alarm', 'reminder', 'notification'] },
      { emoji: '⏰', name: 'alarm clock', keywords: ['time', 'wake up', 'alarm'] },
      { emoji: '⏱️', name: 'stopwatch', keywords: ['time', 'timer', 'race'] },
      { emoji: '📅', name: 'calendar', keywords: ['date', 'schedule', 'plan'] },
    ],
  },
};

export const ALL_CHORE_EMOJIS = Object.values(CHORE_EMOJI_CATEGORIES).flatMap(category => category.emojis);

// Auto-suggest an emoji from the chore name, English and Portuguese.
// Rules are checked in order, so specific things (cama, sapato) must come
// before generic verbs (arrumar, limpar). Keywords are written accent-free
// and matched against an accent-stripped name.
const SUGGESTION_RULES: Array<[string[], string]> = [
  [['teeth', 'tooth', 'dente', 'escova'], '🪥'],
  [['bath', 'banho', 'banheira'], '🛁'],
  [['shower', 'ducha', 'chuveiro'], '🚿'],
  [['wash hands', 'lavar as maos', 'maos'], '🧼'],
  [['hair', 'cabelo'], '💇'],
  [['bed', 'cama'], '🛏️'],
  [['pajama', 'pijama'], '🛌'],
  [['shoe', 'sneaker', 'sapato', 'tenis', 'calcado', 'chinelo'], '👟'],
  [['sock', 'meia'], '🧦'],
  [['laundry', 'clothes', 'roupa'], '🧺'],
  [['dish', 'louca', 'prato'], '🍽️'],
  [['table', 'mesa'], '🍽️'],
  [['cook', 'cozinha'], '🍳'],
  [['groceries', 'compras', 'mercado'], '🍎'],
  [['trash', 'garbage', 'lixo'], '🗑️'],
  [['sweep', 'vacuum', 'varrer', 'aspira', 'vassoura', 'floor', 'chao'], '🧹'],
  [['window', 'janela'], '🪟'],
  [['toy', 'brinquedo', 'lego'], '🧸'],
  [['homework', 'licao', 'tarefa', 'estudar', 'study'], '📚'],
  [['read', 'ler', 'livro', 'book'], '📖'],
  [['backpack', 'mochila'], '🎒'],
  [['dog', 'cachorro'], '🐶'],
  [['cat', 'gato'], '🐱'],
  [['fish', 'peixe'], '🐟'],
  [['plant', 'planta', 'regar', 'flores'], '🌱'],
  [['car', 'carro'], '🚗'],
  [['mail', 'correio'], '📫'],
  [['clean', 'limpar', 'limpeza'], '🧽'],
  [['tidy', 'organizar', 'arrumar', 'guardar', 'put away'], '✨'],
];

const normalizeName = (name: string) =>
  name.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '');

export const suggestChoreEmoji = (name: string): string | null => {
  const normalized = normalizeName(name);
  for (const [keywords, emoji] of SUGGESTION_RULES) {
    if (keywords.some(k => normalized.includes(k))) return emoji;
  }
  return null;
};

// Display helper: chores saved with the generic clipboard get a real emoji
// derived from their name, so pre-readers can recognize the task.
export const getChoreEmoji = (chore: { name: string; emoji?: string }): string =>
  chore.emoji && chore.emoji !== '📋' ? chore.emoji : (suggestChoreEmoji(chore.name) || '📋');

export const searchChoreEmojis = (query: string) => {
  if (!query.trim()) return ALL_CHORE_EMOJIS;

  const searchTerm = query.toLowerCase();
  return ALL_CHORE_EMOJIS.filter(item =>
    item.name.toLowerCase().includes(searchTerm) ||
    item.keywords.some(keyword => keyword.toLowerCase().includes(searchTerm))
  );
};
